### ISSUE TITLE
check_singlebam.pyで既にディレクトリがあるとき

### ISSUE THREAD

**Issue by friend1ws** [aokad/GenomonTCGAkit#1]
エラーになってしまった。

Traceback (most recent call last):
  File "check_singlebam.py", line 267, in <module>
    main()
  File "check_singlebam.py", line 171, in main
    os.removedirs(output_dir + "/result")
  File "/usr/local/package/python2.7/2.7.8/lib/python2.7/os.py", line 170, in removedirs
    rmdir(name)
OSError: [Errno 39] Directory not empty: '/home/omega3/omega_project/check_bam/STAD/result'
[yshira@sc096 GenomonTCGAkit]$ vi check_singlebam.py

**Comment by friend1ws** [comment]
これは新しいバージョンで大丈夫のようですね。
